# Generated by Django 5.1.3 on 2024-12-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0002_remove_user_otp_user_email_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
